const earningsTypes = {
  SET_MONTHLY_INCOME: 'SET_MONTHLY_INCOME',
  SET_ADDITIONAL_INCOME: 'SET_ADDITIONAL_INCOME',
  SET_TOTAL_ANNUAL_PAY: 'SET_TOTAL_ANNUAL_PAY',
  SET_MONTHLY_GROSS_PAY: 'SET_MONTHLY_GROSS_PAY',
  SET_HAVE_ADDITIONAL_INCOME: 'SET_HAVE_ADDITIONAL_INCOME'
};

export default earningsTypes;
