const requestTypes = {
  SET_BUDGET: 'SET_BUDGET',
  SET_CITY_ID: 'SET_CITY_ID',
  SET_STATE_ID: 'SET_STATE_ID',
  SET_PROPERTY_ID: 'SET_PROPERTY_ID',
  SET_PROPERTY_VALUE: 'SET_PROPERTY_VALUE',
  SET_PROPERTY_TYPE_ID: 'SET_PROPERTY_TYPE_ID',
  SET_PROPERTY_BEDROOM: 'SET_PROPERTY_BEDROOM'
};

export default requestTypes;
